default:
  interruptible: true

compile:
  stage: build
  script:
    - pnpm compile
  artifacts:
    paths:
      - build
    untracked: false
    when: on_success
    expire_in: "1 day"

tests:
  stage: test
  needs:
    - compile
  script:
    - pnpm jest --ci --reporters=default --reporters=jest-junit
  artifacts:
    paths:
      - junit.xml
    untracked: false
    when: on_success
    expire_in: "1 day"
