default:
  interruptible: true

.job-template:
  image: node:lts
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - SHELL="$(which bash)" pnpm setup
    - source /root/.bashrc
    - pnpm config set store-dir .pnpm-store
    - pnpm install

contract-compile:
  extends: .job-template
  stage: build
  script:
    - cd contract
    - pnpm blueprint build
  artifacts:
    paths:
      - build
    untracked: false
    when: on_success
    expire_in: "1 day"

contract-tests:
  extends: .job-template
  stage: test
  needs:
    - contract-compile
  script:
    - cd contract
    - pnpm jest --ci --reporters=default --reporters=jest-junit
  artifacts:
    when: on_success
    reports:
      junit:
        - junit.xml
