# FROM mcr.microsoft.com/devcontainers/typescript-node:20
FROM buildpack-deps:bookworm-scm

RUN apt-get update && apt-get install -y xz-utils

SHELL ["/bin/bash", "-c"]

# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -y install --no-install-recommends unzip iputils-ping zsh

# user node
ARG USERNAME=node
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
  && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME -s /bin/bash \
  && apt-get update \
  && apt-get install -y sudo \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME

RUN mkdir -p -m 755 /etc/apt/keyrings && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
  && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
  && sudo apt update \
  && sudo apt install gh -y

RUN apt-get update && apt-get install gnupg2 -y

# ENV HOME /home/node
USER node

# [Optional] Uncomment if you want to install more global node modules
# RUN npm install -g <your-package-list-here>

# nvm
ENV NODE_VERSION=20.11.0
ENV NVM_VERSION=0.39.7

RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh | bash \
  && . ~/.nvm/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && nvm use default

ENV PATH="/home/node/.nvm/versions/node/v$NODE_VERSION/bin:$PATH"

# pnpm
RUN corepack enable \
  && corepack prepare pnpm@latest-8 --activate \
  && SHELL="$(which bash)" pnpm setup \
  && source ~/.bashrc \
  && pnpm config set store-dir $HOME/.pnpm-store

# oh-my-zsh
# RUN wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
# Default powerline10k theme, no plugins installed
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)"

ENV SHELL=/bin/zsh
