version: "3.8"

networks:
  ton-course-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

name: ton-course
services:
  devc:
    # image: mcr.microsoft.com/devcontainers/base:ubuntu
    # profiles: [dev]
    # environment:
    # DATABASE_URL: postgres://hdrc:${POSTGRES_PASSWORD}@db:5432/hdrc
    ports:
      - 5173:5173
    build:
      context: .
      dockerfile: Dockerfile.dev
      # platforms:
      #   - linux/arm64/v8
      # - linux/amd64
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    networks:
      ton-course-network:
        ipv4_address: 10.5.0.2
